version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      # S3 build
      - VITE_BASE_URL=/ npm run build
      - mkdir -p s3-dist ec2-dist
      - cp -r dist/* s3-dist/

      # EC2 build
      - VITE_BASE_URL=/frontend/ npm run build
      - cp -r dist/* ec2-dist/

      # Required by EC2 Deploy action
      - cp postScript.sh ec2-dist/postScript.sh
      - chmod +x ec2-dist/postScript.sh

artifacts:
  files:
    - '**/*'

  secondary-artifacts:
    BuildArtifact:
      base-directory: s3-dist
      files:
        - '**/*'

    BuildArtifactEC2:
      base-directory: ec2-dist
      files:
        - '**/*'